# CI for product catalog
name: product-catalog-ci

on:
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Go 1.22
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Build
        run: |
          cd src/product-catalog
          go mod download
          go build -o product-catalog-service main.go

      - name: unit tests
        run: |
             cd src/product-catalog 
             go test ./... 

  code-quality:
    runs-on: ubuntu-latest

    steps:
        - name: checkout code
          uses: actions/checkout@v4
        
        - name: Run golangci-lint
          run: |
              go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
              golangci-lint run src/product-catalog/...

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Docker
        uses: actions/setup-buildx-action@v2

      - name: Login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Push
        uses: docker/build-push-action@v4
        with:
          context: src/product-catalog
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{github.run_id}}
  

  updatek8s:
    runs-on: ubuntu-latest

    needs: docker

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: update tag in kubernetes deployment manifest
        run: |
          sed -i 's/image:  .*/image: ${{ secrets.DOCKER_USERNAME }}/product-catalog:"${{github.run_id}}"/' kubernetes/productcatalog/deploy.yaml

      - name: commit changes
        run: |
          git config --global user.email "vedharagavan2404@gmail.com"
          git config --global user.name "Vedha Ragavan"
          git add kubernetes/productcatalog/deploy.yaml
          git commit -m [CI]:update image tag to ${{ github.run_id }}"
          git push
        

