name: Docker Compose Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check commit message for [deploy]
        id: check_message
        run: |
          echo "Commit message:"
          git log -1 --pretty=%B
          if ! git log -1 --pretty=%B | grep -iq "\[deploy\]"; then
            echo "No [deploy] flag found in commit message. Skipping deployment."
            exit 1
          fi

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Copy project to server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USERNAME }}/ultimate-devops-CICD

      - name: Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/${{ secrets.SSH_USERNAME }}/ultimate-devops-CICD
            docker compose down
            docker compose up -d --build
          EOF
